namespace Sprig.Codegen.Syntax;

public enum SyntaxKind {
    // Special tokens
    WhitespaceToken,
    EndOfFileToken,
    BadToken,
    IdentifierToken,
    StringToken,
    NumberToken,

    // Simple tokens
    PlusToken,
    MinusToken,
    StarToken,
    SlashToken,
    PercentToken,
    BangToken,
    EqualsToken,
    TildeToken,
    AmpersandToken,
    PipeToken,
    CircumflexToken,
    LeftArrowToken,
    RightArrowToken,
    DotToken,
    CommaToken,
    ColonToken,
    OpenParenthesisToken,
    ClosedParenthesisToken,
    OpenBraceToken,
    ClosedBraceToken,

    // Compound Tokens
    DoubleAmpersandToken,
    DoublePipeToken,
    DoublePlusToken,
    DoubleMinusToken,
    DoubleStarToken,
    DoubleSlashToken,
    DoubleEqualsToken,
    DoubleLeftArrowToken,
    DoubleRightArrowToken,
    DoubleDotToken,
    PlusEqualsToken,
    MinusEqualsToken,
    StarEqualsToken,
    SlashEqualsToken,
    PercentEqualsToken,
    BangEqualsToken,
    AmpersandEqualsToken,
    PipeEqualsToken,
    CircumflexEqualsToken,
    LeftArrowEqualsToken,
    RightArrowEqualsToken,

    // Keywords
    TrueKeyword,
    FalseKeyword,
    LetKeyword,
    VarKeyword,
    IfKeyword,
    ElseKeyword,
    WhileKeyword,
    DoKeyword,
    ForKeyword,
    InKeyword,
    FuncKeyword,
    BreakKeyword,
    ContinueKeyword,
    ReturnKeyword,

    // Expressions
    LiteralExpression,
    NameExpression,
    AssignmentExpression,
    UnaryExpression,
    BinaryExpression,
    ParenthesizedExpression,
    RangeExpression,
    CallExpression,

    // Members
    CompilationUnit,
    GlobalStatement,
    FunctionHeader,
    FunctionParameter,
    
    // Clauses
    TypeClause,
    ElseClause,

    // Statements
    BlockStatment,
    ExpressionStatement,
    VariableDeclaration,
    IfStatement,
    WhileStatement,
    DoWhileStatement,
    ForStatement,
    BreakStatement,
    ContinueStatement,
    ReturnStatement,
}