name: build-project
on: [push]

jobs:
  build:
    name: Build Solution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' 
      
      - name: Restore Dependencies
        run: dotnet restore
      
      - name: Build Solution
        run: dotnet build --configuration Release --no-restore
